### ISSUE TITLE
Support for custom alert actions like i.e. Slack

### ISSUE THREAD

**Issue by janboll** [splunk/terraform-provider-splunk#1]
Hi,

Thank you for putting this project up!

I am interested in using this project, however we need support to use custom alert actions like Slack for instance. https://splunkbase.splunk.com/app/2878/

Do you have custom alert actions on the roadmap?
Or alternatively are you open for contributions?

Thanks,
Jan

**Comment by anushjay** [comment]
Hi @janboll 
Thanks for reaching out. We are in the process of making a list of features to work on for the next release. Can add custom alert actions to it. But will have to get back to you on release dates and details about contributing as well.
