### ISSUE TITLE
Unable to create HEC token on Splunk Cloud.

### ISSUE THREAD

**Issue by anshulgargamway** [splunk/terraform-provider-splunk#120]
Hello Team, We are using resource "splunk_inputs_http_event_collector" to create HEC token.
However, we are unable to create HEC Token although resource execution is successful.
So, we have reached out to splunk support the valid URL to create HEC Token is **/services/dmc/config/inputs/__indexers/http**

But internally Splunk Terraform Provider is using following URL.
/servicesNS/admin/splunk_httpinput/data/inputs/http 

Can you help us with some suggestion on same. This might help us to build business requirement around same.

**Comment by anushjay** [comment]
Please use to ACS provider for Splunk Cloud related operations --
https://github.com/splunk/terraform-provider-splunk/issues/94#issuecomment-1447080407
