### ISSUE TITLE
Plugin did not respond 

### ISSUE THREAD

**Issue by NathanealZheng** [splunk/terraform-provider-splunk#128]
Plan failed for splunk_saved_searches

**Stack Trace**
Stack trace from the terraform-provider-splunk_v1.4.13 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 14 [running]:
github.com/splunk/terraform-provider-splunk/splunk.getSavedSearchesConfigByName({0xc0000412f0, 0x26}, 0xc0004d85a0)
	github.com/splunk/terraform-provider-splunk/splunk/resource_splunk_saved_searches.go:1634 +0x22c
github.com/splunk/terraform-provider-splunk/splunk.savedSearchesRead(0xc0000fc4d0, {0x17c49a0, 0xc000208510})
	github.com/splunk/terraform-provider-splunk/splunk/resource_splunk_saved_searches.go:1008 +0x1d5
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000160360, 0xc0006aa460, {0x17c49a0, 0xc000208510})
	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/resource.go:460 +0x1aa
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00000e068, {0xc00070c180, 0x10af206}, 0xc00070c180)
	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/helper/plugin/grpc_provider.go:525 +0x34b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x18de6c0, 0xc00000e068}, {0x1a85030, 0xc0001ffb90}, 0xc00070c120, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/tfplugin5/tfplugin5.pb.go:3269 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004b6600, {0x1a92000, 0xc0004b6780}, 0xc000212200, 0xc0001ab290, 0x1fc48d0, 0x0)
	google.golang.org/grpc@v1.27.1/server.go:1024 +0xd1e
google.golang.org/grpc.(*Server).handleStream(0xc0004b6600, {0x1a92000, 0xc0004b6780}, 0xc000212200, 0x0)
	google.golang.org/grpc@v1.27.1/server.go:1313 +0xa56
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.27.1/server.go:722 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.27.1/server.go:720 +0xef

Error: The terraform-provider-splunk_v1.4.13 plugin crashed!

**Comment by jdrapss** [comment]
I've run into this issue recently, but no one seems to have an answer / issues are still open related to this. Can I ask how you solved this?
