### ISSUE TITLE
PR #138 reverted PR #133

### ISSUE THREAD

**Issue by mcmluk-monster** [splunk/terraform-provider-splunk#141]
The most recent PR merge #138  reverted the change to omit auto_summarize when empty in PR #133 

https://github.com/mcmluk-monster/terraform-provider-splunk/blob/cfa5ed49d474b1c023d7bf227dbee9fc030ec195/client/models/saved_searches.go#L104

**Comment by mcmluk-monster** [comment]
@anushjay  Are you able to do a hotfix for this?

**Comment by anushjay** [comment]
@mcmluk-monster Argh. Will do.
