### ISSUE TITLE
Support for saved_search argument dispatch.index_earliest

### ISSUE THREAD

**Issue by asvoboda** [splunk/terraform-provider-splunk#15]
In addition to `dispatch.earliest_time`, it is very useful to run some saved searches against the indexed time of a given event stream. The provider should expose `dispatch.index_earliest` as an optional field on saved searches.

I'd be happy to open a PR for this feature, if that is okay :)

**Comment by anushjay** [comment]
Hi @asvoboda 
Thanks for the suggestion and opening a pull request. Appreciate any contributions.
We are adding a Github workflow to run the acceptance tests on every PR. Once we have that merged and running I'll pull in your changes.

**Comment by asvoboda** [comment]
Thanks, sounds good.

Let me know if you'd like me to add any other tests. I'm happy to do so :)

**Comment by anushjay** [comment]
@asvoboda Your changes should be available in v1.3.0 of the provider. Thank you for contributing!
