### ISSUE TITLE
Can this provider be used on splunk cloud with REST endpoint enabled?

### ISSUE THREAD

**Issue by brucetan-displayr** [splunk/terraform-provider-splunk#185]
As the title said, we have splunk cloud instance with REST endpoint enabled, would we be able to use this provider?

**Comment by ojensen5115** [comment]
Yes.

**Comment by jonathanmadeley** [comment]
FYI - I've been stuck on this for a while, hopefully can help someone else. **The provider cannot work with trials or smaller xyz.splunkcloud.com deployments.** The port `8089` is not open on smaller deployments, and ACS is not available on trial deployments either.

Source: https://community.splunk.com/t5/Splunk-Dev/Splunk-SDK-can-t-connect-to-Splunk-Cloud/td-p/178294#answer-305814
