### ISSUE TITLE
Support for Indexer Clusters

### ISSUE THREAD

**Issue by 1733116199** [splunk/terraform-provider-splunk#27]
It seems there are no built-in terraform resource to create an index in an indexer cluster. If I were to do this manually, I would edit  $SPLUNK_HOME/etc/master-apps/_cluster/indexes.conf on the master node of the cluster. 
Is it possible to add this functionality?

**Comment by anushjay** [comment]
Hello @1733116199 
We have received this request from a few others as well. At the moment we don't have a timeline on when this will be available but it is high on the list of endpoints to add. We will respond to your issue as soon as have an idea.
