### ISSUE TITLE
Update go module path to use full github host path

### ISSUE THREAD

**Issue by bhayes-zd** [splunk/terraform-provider-splunk#28]
## Current Issue
> The current module path is `terraform-provider-splunk`. This makes it a tedious process requiring users to clone the repo into their local gopath using `git clone`. It then requires replacing the module path with something like the following to utilize the `splunk` pkg inside this repo as a go module. 
```go
replace github.com/splunk/terraform-provider-splunk => ../../splunk/terraform-provider-splunk 
```

## Proposed Change
> Change the module path in the [go.mod](https://github.com/splunk/terraform-provider-splunk/blob/1bf99a7718046174ebb3ef8142bca88fe38980f1/go.mod#L1) file to `github.com/splunk/terraform-provider-splunk` in order to more easily allow users to leverage your models, clients, and tooling within the [client](https://github.com/splunk/terraform-provider-splunk/tree/master/client) and [splunk](https://github.com/splunk/terraform-provider-splunk/tree/master/splunk) packages.

**Comment by anushjay** [comment]
@bhayes-zd Thanks! Appreciate the suggestion. Will try to get this as soon as we can.

**Comment by anushjay** [comment]
@bhayes-zd 
FYI - Following other providers go mod setup and moving to `github.com/terraform-providers/terraform-provider-splunk`

**Comment by bhayes-zd** [comment]
@anushjay Perfect! I'll keep an eye on #32. Thanks so much.  ❤️
