### ISSUE TITLE
`saved_search` default is_visible to true

### ISSUE THREAD

**Issue by igaskin** [splunk/terraform-provider-splunk#3]
default this to true.  Currently `saved_searches` are hidden by default, making debugging more difficult.  Additionally if a delete operation fails it becomes inconvient to delete the `saved_search` as it is not visible in the UI.

**Comment by anushjay** [comment]
@igaskin Thanks for the suggestion, we can modify the defaults. Manually setting the `is_visible` key to `true` in the saved_searches config should work.

**Comment by igaskin** [comment]
> @igaskin Thanks for the suggestion, we can modify the defaults. Manually setting the `is_visible` key to `true` in the saved_searches config should work.

Understood. This is a request to change the default to `true`, is there a reason why it defaults to `false`?  IMO this is a strange UX to create a saved search that is not visible by default.

**Comment by anushjay** [comment]
@igaskin The flag should default to `true` when the `disabled` flag is set to `false`. May be the field was deprecated at some point because the search is visible though the `is_visible` is set to false. In any case, we will default `is_visible` to `true`.
