### ISSUE TITLE
Module path in wrong organization

### ISSUE THREAD

**Issue by bhayes-zd** [splunk/terraform-provider-splunk#36]
Hey again 😅 

Hate to keep bugging you on this but it appears the [module path that you updated to](https://github.com/splunk/terraform-provider-splunk/blob/15f4e13e79237b96ae4fa4371d2a0df50ef7f86f/go.mod#L1) is for the organization https://github.com/terraform-providers. 

Is that the intended end owner of this repository? If it is, feel free to close this issue.

But if the repository is going to stay under https://github.com/splunk/terraform-provider-splunk then the module path should be `github.com/splunk/terraform-provider-splunk` since Splunk is the parent org of the repository. Otherwise, `go get` will search for your repo in an org where it doesn't exist. 

Sorry to bug ya again on the same issue, just wanna make sure I didn't cause confusion with my last request. Thanks!

**Comment by anushjay** [comment]
@bhayes-zd Ah yes, that makes sense. 🤦🏾 
Thanks for catching this.
