### ISSUE TITLE
TestAccCreateSplunkIndex is randomly failing

### ISSUE THREAD

**Issue by zscholl** [splunk/terraform-provider-splunk#39]
See this run: https://github.com/splunk/terraform-provider-splunk/runs/1421820937

Forcing the test to re-run resolved the test with no changes to code.

**Comment by nstonesplunk** [comment]
Deletion of indexes is asynchronous which causes these intermittent errors. Adding in a wait (~2 seconds) fixes this and should now be in the main branch. You may need a longer wait if the environment is busy but 2 seconds seems to resolve the issue most of the time.
