### ISSUE TITLE
Specifying an application context in acl{} requires the app directory to exist before 'terraform apply'

### ISSUE THREAD

**Issue by yorokobi** [splunk/terraform-provider-splunk#4]
A file system resource that includes an `acl{}` block specifying an app context should create that app context if it does not exist. Alternatively, the "splunk_apps_local" resource should be extended to lay the groundwork to create a new app directory structure in `$SPLUNK_HOME/etc/apps/` in addition to installing apps from Splunkbase/.tgz/.spl/etc.

Example .tf:
```hcl
terraform {
  required_providers {
    splunk = {
      source = "splunk/splunk"
      version = "1.0.0"
    }
  }
}

provider "splunk" {
  url = "localhost:8089"
  username = "admin"
  password = "changeme"
}

resource "splunk_indexes" "tf-index" {
  name = "tf-index"
  frozen_time_period_in_secs = 84200
  acl {
    app = "terraform"
    sharing = "global"
    read    = ["*"]
    write   = ["admin"]
  }
}
```

If `$SPLUNK_HOME/etc/apps/terraform` does not exist (and Splunk restarted if it is a new directory), `terraform apply` will fail with:

```sh
Error: Http Error: [404] 404 Not Found {"messages":[{"type":"ERROR","text":"Action forbidden."}]}

  on test.tf line 16, in resource "splunk_indexes" "tf-index":
  16: resource "splunk_indexes" "tf-index" {
```

**Comment by anushjay** [comment]
Hi @yorokobi 
Thanks for your suggestion. We will look into the possible ways of creating app namespaces based on dependency. Not sure if you've already tried this out but the `splunk_local_apps` resource should be able to create a generic splunk app folder structure and you can also use the `depends_on` flag to order the execution.

**Comment by yorokobi** [comment]
Okay. I see that this does the trick (and should probably be called out in the documentation):

```hcl
terraform {
  required_providers {
    splunk = {
      source = "splunk/splunk"
      version = "1.0.0"
    }
  }
}

provider "splunk" {
  version = "1.0.0"
  url = "localhost:8089"
  username = "admin"
  password = "changeme"
}

resource "splunk_apps_local" "terraform_index_app" {
  name = "terraform"
  acl {
    sharing = "global"
    read    = ["*"]
    write   = ["admin"]
  }
}

resource "splunk_indexes" "terraform" {
  name = "terraform"
  acl {
    app = "terraform"
  }
  depends_on = [
    splunk_apps_local.terraform_index_app
  ]
}
```

The resulting file structure (provided by `splunk_apps_local`) is a bit over the top for creating apps destined for a Deployment Server or Cluster Master.

```plain
[splunk@lab] ~ % tree etc/apps/terraform/
etc/apps/terraform/
├── bin
│   └── README
├── default
│   ├── app.conf
│   └── data
│       └── ui
│           ├── nav
│           │   └── default.xml
│           └── views
│               └── README
├── local
│   ├── app.conf
│   └── indexes.conf
└── metadata
    ├── default.meta
    └── local.meta

8 directories, 8 files
```

**Comment by anushjay** [comment]
@yorokobi 
Glad that worked for you. About the app folder structure, Splunk currently only offers two types of app templates `barebones` (default) and `sample_app` (with view and navs). (I found this in the REST API docs).
The example main.tf showcases `depends_on` flag but we will try to document it better. Thanks!

**Comment by yorokobi** [comment]
Thank you, Anush. 🙏🏻

My meaning behind "called out in the docs" was intended to address the problem in the original post: `acl{}` does not have the capacity to create directories for apps that do not exist and, therefore, one must use the `splunk_apps_local` resource to create them beforehand.

I will leave it to your judgement as to whether this issue can/should be closed. There is a way to achieve what I wanted with `splunk_apps_local` as you correctly pointed out.

**Comment by anushjay** [comment]
@yorokobi your welcome. This seems like a common suggestion for creating knowledge objects for non-existing users. (https://docs.splunk.com/Documentation/SplunkCloud/latest/RESTTUT/RESTandCloud#Create_empty_apps_to_store_knowledge_objects)

I will close this issue for now since we are not sure if this will be addressed immediately as there is a workaround. Appreciate you following up on this. Feel free to add issues/suggestions when you come across any in the future.
