### ISSUE TITLE
Splunk - is there a way download the provider package and use as a local plugin

### ISSUE THREAD

**Issue by tommyreilly** [splunk/terraform-provider-splunk#43]
Hi,

The company I work for restrict downloads of provider versions from the external (terraform) registry and we need to prepackage any terraform providers we use in a local directory. We do not allow dynamic updates from the internet to other providers or later  versions of providers that have not been "vetted" internally.

We would like to use the new Splunk provider but unless we can download as other providers are available from https://releases.hashicorp.com/ and include in our own local installation , then we are restricted to not make it available to our product teams.

https://releases.hashicorp.com/

Are there any plan to make the Splunk provider available in this same manner?

Thanks in advance.

Tommy

**Comment by anushjay** [comment]
Hi @tommyreilly 
We keep Splunk provider publicly available and up to date in the latest terraform registry -> https://registry.terraform.io/providers/splunk/splunk/latest

The binaries are available here -> https://github.com/splunk/terraform-provider-splunk/releases. Are you able to access this link?

**Comment by tommyreilly** [comment]
@anushjay - thank you so much, that is perfect.

Appreciate it
