### ISSUE TITLE
Unable to create a Metric index

### ISSUE THREAD

**Issue by arnaudouttiercloudreach** [splunk/terraform-provider-splunk#48]
With provider version 1.3.7, when I try to create a simple Metric index like this :

```
resource splunk_indexes metrics_index {
  name     = "metrics" 
  datatype = "metric"
}
```

I get this error :

`Error: Unable to find resource: metrics`.

I have no error with `event` datatype indexes.

**Comment by nstonesplunk** [comment]
Looks like metrics indexes can be successfully created but the provider fils to read/list them as the endpoint defaults to only listing indexes with the 'event' datatype.

Fix in progress: https://github.com/splunk/terraform-provider-splunk/pull/50
