### ISSUE TITLE
Authentication issues starting at 1.3.3

### ISSUE THREAD

**Issue by infoseckyle** [splunk/terraform-provider-splunk#49]
I get the following errors when jumping between provider versions 1.3.2 and 1.3.3. It's weird because it only seems to happen when the API is fronted by an AWS ELB. 

Running Splunk 7.2.6

```

$ terraform plan -out=$PLAN_DEV -var-file="terraform/env-dev.tfvars" ./terraform

 Refreshing Terraform state in-memory prior to plan...
 The refreshed state will be used to calculate this plan, but will not be
 persisted to local or remote state storage.
 splunk_saved_searches.AUDIT-0001: Refreshing state... [id=<Redacted>]
 splunk_saved_searches.AUDIT-0004: Refreshing state... [id=<Redacted>]
 splunk_saved_searches.AUDIT-0003: Refreshing state... [id=<Redacted>]
 Error: Http Error: [401] 401 Unauthorized {"messages":[{"type":"WARN","text":"call not properly authenticated"}]}
 Error: Http Error: [401] 401 Unauthorized {"messages":[{"type":"WARN","text":"call not properly authenticated"}]}
 Error: Http Error: [401] 401 Unauthorized {"messages":[{"type":"WARN","text":"call not properly authenticated"}]}
Cleaning up file based variables

```

**Comment by anushjay** [comment]
Hi @infoseckyle 
Looking at the changelog, 1.3.3 doesn't have any authentication-related changes. Though v1.3.4 revert some mod path changes and that shouldn't be related to this issue either. Are you seeing this with the latest v1.3.8 as well? If so, we might have to test this scenario out. ELB shouldn't cause an issue as long as you have valid certs.

**Comment by infoseckyle** [comment]
1.3.8 doesn't work either. Certs are valid.

**Comment by anushjay** [comment]
@infoseckyle There is only a single instance behind the ELB, correct?

**Comment by infoseckyle** [comment]
It's actually a 3 node SHC. I can try a single SH when I'm back in the office on Monday.

**Comment by infoseckyle** [comment]
This issue is still occurring with 1.3.9. I did some testing; reduced the ELB pool to just one target. When reviewing the Search Head logs it appears the first request is successful, but the second request isn't:

`
10.10.10.105 - api [03/Mar/2021:16:10:11.726 +0000] "POST /services/auth/login?count=-1&output_mode=json HTTP/1.1" 200 148 - - - 8ms
Audit:[timestamp=03-03-2021 16:10:11.733, user=api, action=login attempt, info=succeeded, src=10.10.10.105][n/a]
10.10.10.105 - - [03/Mar/2021:16:10:11.761 +0000] "GET /servicesNS/-/-/saved/searches?count=-1&output_mode=json HTTP/1.1" 401 71 - - - 0ms
Audit:[timestamp=03-03-2021 16:10:11.761, user=n/a, action=read_session_token, info=denied, reason="cannot decrypt token"][n/a]
`

**Comment by markdingram** [comment]
confirmed that this issue is resolved for my setup with v.1.4.6

@infoseckyle are you able to try with v1.4.6?

**Comment by infoseckyle** [comment]
Yes, it's working on this version.
