### ISSUE TITLE
Can the provider be published on https://releases.hashicorp.com?

### ISSUE THREAD

**Issue by PaarthB** [splunk/terraform-provider-splunk#78]
Hi,

Is there a reason why this provider is not yet publically available to install the binary through https://releases.hashicorp.com ? This will be really helpful to share with everyone, who just want to use it, without having to build it manually themselves. 

Are there any plans to add it, and by when?

**Comment by anushjay** [comment]
@PaarthB 
All different binaries of earlier releases of the Splunk provider can be found on our Github releases -> https://github.com/splunk/terraform-provider-splunk/releases
According to Hashicorp, starting with 0.13 provider binaries are now hosted by the registry (and proxied to GitHub). Hope this helps.
