### ISSUE TITLE
Add support for the Splunk Cloud Admin Config Service (ACS) API

### ISSUE THREAD

**Issue by JosephHobbs** [splunk/terraform-provider-splunk#94]
Splunk Cloud has recently announced/released new capabilities to the ACS API.  It would be great if these were available via this Terraform provider!

- Configure IP allow lists
- Configure outbound ports
- Manage HTTP Event Collector tokens
- Manage indexes
- Manage private apps

More information is available at <https://docs.splunk.com/Documentation/SplunkCloud/8.2.2109/Config/ACSREF>

Thank you!

**Comment by micahkemp-splunk** [comment]
ACS may justify having its own Terraform provider, as it uses a different service than vanilla `splunkd`, which is what this provider uses.

**Comment by JosephHobbs** [comment]
To be honest, I was thinking the same thing...

**Comment by pabbyt** [comment]
Do we know if this is something that is in the works? If not, do you think that opening a PR against this repo would be the way to go (modifying the client to work with the ACS API as well), or creating a wholly new provider.

**Comment by mausam-patel** [comment]
We are excited to announce the first release of the [Terraform Provider for Splunk Cloud](https://registry.terraform.io/providers/splunk/scp/latest) to allow automated, scalable configuration management for multiple Splunk Cloud deployments, hybrid use cases, and other services (such as AWS). The provider interacts with [ACS API](https://docs.splunk.com/Documentation/SplunkCloud/9.0.2209/Config/ACSIntro) endpoints and currently supports the Indexes resource for both Classic and Victoria experiences. 


Documentation for resources supported by the provider, as well as troubleshooting and tips, can be found [here](https://registry.terraform.io/providers/splunk/scp/latest) and in the [Github Repo](https://github.com/splunk/terraform-provider-scp). As this is an iterative project, we request that you submit feature requests in the [Splunk Ideas](https://login.splunk.com/?redirecturl=https%3A%2F%2Flogin.splunk.com%2Fsso%2Fdispatch%3Ftype%3Daha%26fromURI%3Dhttps%253A%252F%252Fidp.login.splunk.com%252Fapp%252Fsplunkext_ideasaha_1%252Fexk7pkzsn9kR0rJHc2p7%252Fsso%252Fsaml%253FSAMLRequest%253DhZLNTuswEEZfJTuvEidpSm%25252BtplJFhSiCK1R%25252BFmyqqTOhVhzbeBxu4elJUxDcBbDxwjpzvk9jzwha7cSiCzuzxqcOKUQLIvRBWXNqDXUt%25252Bhv0z0ri3fqyZLsQHAnOyenONKpCoOR4wg4SZTn0Kn6wcglab0E2LFr2WmXg4Pw0qMol2j4qkxxdibQtB%25252Bfe1bgPm0HcezcZx30zcc0rmWmzTv3FuczdhBPZIYpFq2XJNvW2Oqkm0zSWW%25252FgTF1vM42k1zuPiZDyGoi5GaV33KFGHK0MBTChZnuajOM3jvLjNpmI0Eln2wKJ79DSUzZOURftWGxKHoJJ13ggLpEgYaJFEkOJmcXUpelDAx%25252BK%25252BjrifZ5y3wUqr2Xx2oMXQzs9%25252FXfOMf8Vnx2f82%25252BtXy2urlXyJFlrbf6ceIWDJgu%25252BQRWfWtxC%25252BL5Ql2XCjqrgeUNEZcihVrbBifH4M%25252Ff%25252B7zN8A) portal under Enterprise Cloud, and report any issues with the provider on our repo in Github. We will continue to add support for new resources, as well as update existing resources to work towards a mature, stable provider for Splunk Cloud Platform.
